### ISSUE TITLE
Percentual Change not valid when SAME VOLUME selected for fg and bg

### ISSUE THREAD

**Issue by che85** [fedorov/MultiVolumeExplorer#24]
When selecting the SAME VOLUME for background and foreground, the relative change of both (lines and points) to baseline shall be the same.

<img width="729" alt="screenshot 2015-08-12 10 32 27" src="https://cloud.githubusercontent.com/assets/10195822/9226689/bfbd8f7a-40dd-11e5-8bee-8c0aa2958603.png">

**Comment by che85** [comment]
I am going to fix this after extracting functionality for PCampReview

**Comment by fedorov** [comment]
Looks like the secondary volume is just showing the signal, not normalized. The 2-volume feature was added later and apparently never tested in percent mode ...
