### ISSUE TITLE
Legend would make sense when using more than one multi volume

### ISSUE THREAD

**Issue by che85** [fedorov/MultiVolumeExplorer#25]
That would make more sense since unexperienced users cannot know which of both (points or line) represent the 1st and 2nd volume. 

This makes the application much more useful. 

I would like to add another checkbox for "show legend"

**Comment by fedorov** [comment]
Makes sense, go ahead

---

**Comment by che85** [comment]
Fixed. Also reorganized GUI elements for better overview.

<img width="1680" alt="screenshot 2015-08-14 14 14 38" src="https://cloud.githubusercontent.com/assets/10195822/9281232/8ae37098-4291-11e5-83e9-c441e38558bb.png">
